const assert=Object.assign((value:unknown,message='Assertion failed')=>{if(!value)throw Error(message);},{
 equal:(a:unknown,b:unknown,message='Values differ')=>{if(!Object.is(a,b))throw Error(message+': '+JSON.stringify(a)+' != '+JSON.stringify(b));},
 deepEqual:(a:unknown,b:unknown)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error('Structures differ');},
 throws:(run:()=>unknown)=>{let caught=false;try{run();}catch{caught=true;}if(!caught)throw Error('Expected a failure');},
 rejects:async(run:Promise<unknown>,pattern:RegExp)=>{let caught=false;try{await run;}catch(e){caught=true;if(!pattern.test((e as Error).message))throw e;}if(!caught)throw Error('Expected rejection');}
});
import { GapQueue, type GapTransport } from './gapQueue';
import { evidencePath, gapCounts, gapResize, sameGap, visibleGaps, type Evidence, type Gap, type GapSnapshot } from './gapWorkflow';
import { combinedFeedback, withGapStatus } from './gapPresentation';
const U='10000000-0000-4000-8000-000000000001',P='20000000-0000-4000-8000-000000000001',G='30000000-0000-4000-8000-000000000001';
const time='2026-10-04T12:00:00.000Z';
const makeGap=(n=2):Gap=>({id:G,user_id:U,project_id:P,building:'A',floor_area:'2',unit_location:'Room 201',category:'Missing device',description:'Synthetic missing device fixture',status:'open',photo_count:n,created_at:time,updated_at:time,resolved_at:null,deletion_requested_at:null});
const photo=(i:number):Evidence=>{const id='40000000-0000-4000-8000-'+String(i).padStart(12,'0');return {metadata:{id,user_id:U,project_id:P,entity_type:'gap',entity_id:G,storage_path:evidencePath(U,P,G,id),file_name:'evidence.jpg',mime_type:'image/jpeg',file_size:1200,created_at:time},local_uri:'file:///documents/gap-evidence/'+U+'/'+G+'/'+id+'.jpg',state:'pending',error:'',retries:0};};
function disk(){const data=new Map<string,string>();let fail=false;return {data,fail:(v:boolean)=>{fail=v;},getItem:async(k:string)=>data.get(k)??null,setItem:async(k:string,v:string)=>{if(fail)throw Error('Disk write failed');data.set(k,v);}};}
const copy=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
function transport(){const gaps=new Map<string,Gap>(),files=new Map<string,Evidence>(),removed:string[]=[];const t:GapTransport={saveGap:async g=>{gaps.set(g.id,copy(g));return copy(g);},saveFile:async f=>{files.set(f.metadata.storage_path,copy(f));return copy(f.metadata);},deleteGap:async g=>{gaps.delete(g.id);files.clear();},removeLocal:async f=>{removed.push(f.local_uri);}};return {t,gaps,files,removed};}
const snapshotDevices={version:1 as const,items:[],devices:[],projects:[],pro:true,checkedAt:''};
export async function runGapChecks(){
 assert.deepEqual(gapResize(6000,4000),{width:1800});assert.deepEqual(gapResize(3000,5000),{height:1800});assert.equal(gapResize(800,900),null);assert.throws(()=>gapResize(0,400));
 const d=disk(),q=new GapQueue(d,U);await q.open();await q.enqueue(makeGap(),[photo(1),photo(2)]);const reopened=new GapQueue(d,U);await reopened.open();assert.deepEqual(reopened.read().items[0].files.map(f=>f.metadata.id),[photo(1).metadata.id,photo(2).metadata.id]);assert.equal(reopened.read().items[0].state,'pending');
 const cloud=transport();let lost=true,uploadCalls=0;const retry={...cloud.t,saveFile:async(f:Evidence)=>{uploadCalls++;const ack=await cloud.t.saveFile(f);if(lost){lost=false;throw Error('Network lost after upload');}return ack;}};
 await reopened.sync(retry,()=>true);assert.equal(reopened.read().items[0].state,'failed');assert.equal(reopened.read().items[0].files[0].state,'failed');assert.equal(cloud.removed.length,0);assert.equal(cloud.files.size,1);assert.equal(combinedFeedback({failed:1,attempted:1,confirmed:0},snapshotDevices,reopened.read(),true).phase,'failure');
 await reopened.sync(retry,()=>true,true);assert.equal(reopened.read().items[0].state,'uploaded');assert.equal(cloud.gaps.size,1);assert.equal(cloud.files.size,2);assert.equal(uploadCalls,3);assert.equal(gapCounts(reopened.read()).uploaded,3);
 await reopened.setStatus(makeGap(),'resolved');assert.equal(reopened.read().items[0].gap.resolved_at!==null,true);await reopened.sync(cloud.t,()=>true);assert.equal(cloud.gaps.get(G)?.status,'resolved');assert.equal(cloud.removed.length,0);await reopened.setStatus(reopened.read().items[0].gap,'open');await reopened.sync(cloud.t,()=>true);assert.equal(cloud.gaps.get(G)?.status,'open');
 let cleanupFails=true;await reopened.remove(reopened.read().items[0].gap);const deletion={...cloud.t,deleteGap:async(g:Gap,fs:Evidence[])=>{if(cleanupFails){cleanupFails=false;throw Error('Storage cleanup denied');}await cloud.t.deleteGap(g,fs);}};
 await reopened.sync(deletion,()=>true);assert.equal(reopened.read().items[0].state,'failed');assert.equal(cloud.files.size,2);assert.equal(cloud.removed.length,0);assert.equal(visibleGaps(reopened.read()).length,0);
 await reopened.sync(deletion,()=>true,true);assert.equal(reopened.read().items.length,0);assert.equal(cloud.files.size,0);assert.equal(cloud.gaps.size,0);assert.equal(cloud.removed.length,2);
 const fd=disk(),failedQueue=new GapQueue(fd,U);await failedQueue.open();fd.fail(true);await assert.rejects(failedQueue.enqueue(makeGap(),[photo(1),photo(2)]),/Disk/);assert.equal(failedQueue.read().items.length,0);fd.fail(false);
 await assert.rejects(failedQueue.enqueue({...makeGap(),user_id:P},[photo(1),photo(2)]),/account/);await assert.rejects(failedQueue.enqueue(makeGap(),[photo(1)]),/one and three/);await assert.rejects(failedQueue.enqueue(makeGap(),[photo(1),photo(1)]),/one and three/);
 await failedQueue.enqueue(makeGap(1),[photo(1)]);let release!:()=>void;const wait=new Promise<void>(r=>{release=r;});const slow={...cloud.t,saveGap:async(g:Gap)=>{await wait;return copy(g);}};const one=failedQueue.sync(slow,()=>true),two=failedQueue.sync(slow,()=>true);assert.equal(one,two);assert.equal(failedQueue.read().items[0].state,'pending');await Promise.resolve();release();await one;
 const ackDisk=disk(),ackQueue=new GapQueue(ackDisk,U);await ackQueue.open();await ackQueue.enqueue(makeGap(1),[photo(1)]);await ackQueue.sync({...cloud.t,saveGap:async g=>({...g,unit_location:'Incorrect server value'})},()=>true);assert.equal(ackQueue.read().items[0].state,'failed');assert.equal(ackQueue.read().items[0].files[0].state,'pending');
 await ackQueue.sync({...cloud.t,saveFile:async f=>({...f.metadata,file_size:1})},()=>true,true);assert.equal(ackQueue.read().items[0].state,'failed');
 const raceDisk=disk(),raceQueue=new GapQueue(raceDisk,U);await raceQueue.open();await raceQueue.enqueue(makeGap(1),[photo(1)]);let start!:()=>void,end!:()=>void;const started=new Promise<void>(r=>{start=r;}),gate=new Promise<void>(r=>{end=r;});const raceCloud=transport();let first=true;
 const race=raceQueue.sync({...raceCloud.t,saveFile:async f=>{if(first){first=false;start();await gate;}return raceCloud.t.saveFile(f);}},()=>true);
 await started;await raceQueue.setStatus(makeGap(1),'resolved');await raceQueue.cache([],[],time);assert.equal(raceQueue.read().items.length,1);end();await race;assert.equal(raceQueue.read().items[0].gap.status,'resolved');assert.equal(raceCloud.gaps.get(G)?.status,'resolved');assert.equal(raceQueue.read().items[0].state,'uploaded');
 const remoteQueue=new GapQueue(disk(),U);await remoteQueue.open();const remoteGap=makeGap(1);const remoteFile={...photo(1).metadata};await remoteQueue.cache([remoteGap],[remoteFile],time);await remoteQueue.setStatus(remoteGap,'resolved');const remoteReopen=new GapQueue({getItem:async()=>JSON.stringify(remoteQueue.read()),setItem:async()=>{}},U);await remoteReopen.open();await remoteReopen.sync(transport().t,()=>true);assert.equal(remoteReopen.read().items[0].state,'uploaded','remote confirmed photos need no local URI');
 const refreshedRemote=remoteReopen.read().items[0].gap;await remoteReopen.cache([{...refreshedRemote,status:'open',resolved_at:null}],[remoteFile],time);assert.equal(visibleGaps(remoteReopen.read())[0].status,'open','a confirmed local copy reflects another phone’s status');
 const tombQueue=new GapQueue(disk(),U);await tombQueue.open();await tombQueue.enqueue(makeGap(1),[photo(1)]);await tombQueue.cache([],[],time,undefined,[{user_id:U,project_id:P,gap_id:G,created_at:time}]);let saves=0;await tombQueue.sync({...cloud.t,saveGap:async g=>{saves++;return g;}},()=>true);assert.equal(saves,0);assert.equal(tombQueue.read().items.length,0);
 const corrupted=copy(raceQueue.read());corrupted.items[0].gap.user_id=P;await assert.rejects(new GapQueue({getItem:async()=>JSON.stringify(corrupted),setItem:async()=>{}},U).open(),/account/);
 await assert.rejects(raceQueue.cache([],[],time,undefined,[{user_id:P,project_id:P,gap_id:G,created_at:time}]),/another account/);
 const restartDisk=disk(),restartQueue=new GapQueue(restartDisk,U);await restartQueue.open();await restartQueue.enqueue(makeGap(1),[photo(1)]);const interrupted=restartQueue.read();interrupted.items[0].state='uploading';interrupted.items[0].files[0].state='uploading';await restartDisk.setItem('cablemint.gap-journal.v1.'+U,JSON.stringify(interrupted));const restart=new GapQueue(restartDisk,U);await restart.open();assert.equal(restart.read().items[0].state,'pending');assert.equal(restart.read().items[0].files[0].state,'pending');
 assert.equal(withGapStatus('Synced',restart.read()),'Pending');assert.equal(withGapStatus('Synced',{...restart.read(),items:[],gaps:[makeGap(2)],files:[photo(1).metadata]}),'Pending','partial remote evidence never claims Synced');
 const partialCloud={...restart.read(),items:[],gaps:[makeGap(2)],files:[photo(1).metadata]};assert.equal(combinedFeedback({failed:0,attempted:0,confirmed:0},snapshotDevices,partialCloud,true).phase,'idle','partial remote evidence must not produce green synced feedback');
 assert(sameGap(makeGap(),{...makeGap(),created_at:'2026-10-04T12:00:00+00:00'}));
 console.log('Gap/photo journal: offline restart, interrupted uploads, single worker, stable retry paths, failed evidence retention, full acknowledgement, resolve/reopen, safe deletion, account isolation and cross-phone deletion protection passed');
}
